### ISSUE TITLE
Lighter colors for dark colorscheme

### ISSUE THREAD

**Issue by ghost** [owickstrom/vim-colors-paramount#10]
It looks like high contrast colorscheme in dark one. I think I'll send pr to change colors.

**Comment by owickstrom** [comment]
Hi,

Can you provide an example of what you thing is bad? If you just don't like the color choices you're welcome to fork the project.

**Comment by ghost** [comment]
Background is really dark
Purple is dark like background

But others are good.

**Comment by owickstrom** [comment]
OK, this is something that's not going to change. Please instead fork the colorscheme, as many others have done to tweak it to their personal preferences.
