### ISSUE TITLE
emacs port

### ISSUE THREAD

**Issue by rofrol** [owickstrom/vim-colors-paramount#12]
I really like your colors scheme. Do you know of emacs port of this?

**Comment by owickstrom** [comment]
Thanks! I don't know of any straight port, but you could most likely tweak https://github.com/anler/minimal-theme to get close. I've used that one in Emacs.

**Comment by rofrol** [comment]
Thanks. I already looked at this theme as was recommended here https://www.reddit.com/r/emacs/comments/3oc7jk/nice_emacs_themes_with_a_limited_number_of_colors/
