### ISSUE TITLE
Background color bug using '/' (forward slash) on commented code

### ISSUE THREAD

**Issue by lerrua** [owickstrom/vim-colors-paramount#4]
Hi,

First of all, thanks for the theme. I really like it.
But using dark background I have a bug when a search a word using `/`, if that word is inside a commented line, it's turns like a "invisible" mark for me.

In this example bellow I'm using `/ sh`:
![vim screenshot from 2017-08-15 18-00-01](https://user-images.githubusercontent.com/154603/29336370-ef1d1c42-81e3-11e7-97b0-57037cfc6df8.png)

For now I'm using neovim and gnome-terminal.
Thanks.

**Comment by owickstrom** [comment]
Hi! I've had that problem as well, and I fixed it by using a green background for search highlights. I forgot to push it however, but it's on `master` now. Please try it and see if it works for you.
Thanks!

**Comment by owickstrom** [comment]
Closing this now, please reopen if you any more trouble with it.
